### POST User registation
POST http://localhost:8080/v1/registration
Content-Type: application/json

{
  "email": "emersonrjr03@gmail.com",
  "password": "any_password",
  "passwordConfirmation": "any_password",
  "name": "any_name",
  "birthDate": "2022-04-09"
}

### GET Token Confirmation
POST http://localhost:8080/v1/registration/confirm?token={token}
Content-Type: application/json

### GET User details
GET http://localhost:8080/v1/user/{userId}
Accept: application/json
