GET http://localhost:8080/v1/user
Accept: application/json

###
GET http://localhost:8080/v1/user/1
Accept: application/json


### POST User registation
POST http://localhost:8080/v1/user
Content-Type: application/json

{
  "email": "invalid_email@@.com",
  "password": "any_password",
  "passwordConfirmation": "any_password",
  "birthDate": "09-04-2022"
}

###